defaults:
  - defaults

args:
  home: ""
  data_dir: "${args.home}/rds_work/datasets" #"/home/gb511/datasets" 
  log_dir: "${args.home}/rds_work/projects/scoreVAE/experiments/gd_cifar10/" #"/home/gb511/projects/scoreVAE/experiments/cifar10" 
  log_name: "encoder_low_beta" 
  phase: "train"
  accelerator: 'gpu'
  batch_size: 128
  lr: 1e-5 # low learning rate
                      
  lr_anneal_steps: 2500
  dataset: "cifar10"
  accumulate_grad_batches: 1
  grad_clip: 1
                      
  attention_resolutions: 32,16,8
  class_cond: False
  diffusion_steps: 1000
  image_size: 32
  learn_sigma: False
                      
  dropout: 0.3
  noise_schedule: "cosine"
  num_channels: 128
  num_head_channels: 64
  num_res_blocks: 2
  resblock_updown: True
                      
  use_fp16: False
  use_scale_shift_norm: True
  #/home/gb511/projects/scoreVAE/experiments/cifar10/prior/checkpoints/epoch=347-step=122496.ckpt 
  
  diffusion_model_checkpoint: ${args.home}/rds_work/projects/scoreVAE/experiments/gd_cifar10/simple_prior/checkpoints/epoch=936-step=329824.ckpt
  resume_checkpoint: null #${args.home}/rds_work/projects/scoreVAE/experiments/gd_cifar10/encoder_simple/checkpoints/epoch=124-step=44000.ckpt

  #ScoreVAE settings
  beta: 1e-8 # low beta
  ema_rate: "0.999" # using low EMA
  scoreVAE_training_loss: 'simple'
  latent_dim: 384
  encoder_use_fp16: False
  encoder_width: 128
  encoder_depth: 2
  encoder_attention_resolutions: 32,16,8
  encoder_use_scale_shift_norm: True              
  encoder_resblock_updown: True
  encoder_pool: attention
  encoder_type: 'ConvNet'