defaults:
  - defaults
args:
  data_dir: "${args.home}/rds_work/datasets"
  log_dir: "/store/CIA/js2164/models/gd_cifar10"
  log_name: "encoder" 
  phase: "test" 
  batch_size: 128 
  lr: 1e-4
                      
  lr_anneal_steps: 5000
  dataset: "cifar10"
  accumulate_grad_batches: 1
  grad_clip: 1
                      
  attention_resolutions: 32,16,8
  class_cond: False
  diffusion_steps: 1000
  image_size: 32
  learn_sigma: True
                      
  dropout: 0.3
  noise_schedule: "cosine"
  num_channels: 128
  num_head_channels: 64
  num_res_blocks: 2
  resblock_updown: True
                      
  use_fp16: False
  use_scale_shift_norm: True
  diffusion_model_checkpoint: /store/CIA/js2164/models/gd_cifar10/prior/checkpoints/epoch=347-step=122496.ckpt
                      
  latent_dim: 384
  encoder_use_fp16: False
  encoder_width: 128
  encoder_depth: 2
  encoder_attention_resolutions: 32,16,8
  encoder_use_scale_shift_norm: True              
  encoder_resblock_updown: True
  encoder_pool: attention